# HTTP 连接配置 TODO
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

# 腾讯云账号相关的信息配置 TODO
tencent:
  sms:
    account:
      secret-id: "AKIDiEUt30g7LK2UikaCtOdeS4e7MM7du072"
      secret-key: "uAOVWVJsBC8qISVN5ZR9cpohV8VfhkZB"
      sign-name: "xiekun个人公众号"
      sms-sdk-app-id: "1400792521"
      template-id: "1676998"